[package]
name = "tao"
version = "0.24.1"
description = "Cross-platform window manager library."
authors = [
  "Tauri Programme within The Commons Conservancy",
  "The winit contributors"
]
edition = "2021"
rust-version = "1.56"
keywords = [ "windowing" ]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tauri-apps/tao"
documentation = "https://docs.rs/tao"
categories = [ "gui" ]

[package.metadata.docs.rs]
features = [ "rwh_04", "rwh_05", "rwh_06", "serde" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
  "i686-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[features]
default = [ "rwh_06" ]

[workspace]
members = [ "tao-macros" ]

[build-dependencies]
cc = "1"

[dependencies]
instant = "0.1"
lazy_static = "1"
libc = "0.2"
log = "0.4"
serde = { version = "1", optional = true, features = [ "serde_derive" ] }
rwh_04 = { package = "raw-window-handle", version = "0.4", optional = true }
rwh_05 = { package = "raw-window-handle", version = "0.5", features = [ "std" ], optional = true }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = [ "std" ], optional = true }
bitflags = "1"
crossbeam-channel = "0.5"
url = "2"

[dev-dependencies]
image = "0.24"
env_logger = "0.10"

[target."cfg(any(target_os = \"android\", target_os = \"windows\"))".dependencies]
once_cell = "1"

[target."cfg(target_os = \"android\")".dependencies]
jni = "0.21"
ndk = "0.7"
ndk-sys = "0.4"
ndk-context = "0.1"
tao-macros = { version = "0.1.0", path = "./tao-macros" }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
objc = "0.2"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.25"
core-foundation = "0.9"
core-graphics = "0.23"
dispatch = "0.2"
scopeguard = "1.2"
png = "0.17"

[target."cfg(target_os = \"windows\")".dependencies]
parking_lot = "0.12"
unicode-segmentation = "1.10"
image = { version = "0.24", default-features = false }
windows-implement = "0.52"
windows-version = "0.1"

  [target."cfg(target_os = \"windows\")".dependencies.windows]
  version = "0.52"
  features = [
  "implement",
  "Win32_Devices_HumanInterfaceDevice",
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_DataExchange",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_Ole",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_System_WindowsProgramming",
  "Win32_System_SystemInformation",
  "Win32_UI_Accessibility",
  "Win32_UI_Controls",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_Ime",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Input_Pointer",
  "Win32_UI_Input_Touch",
  "Win32_UI_Shell",
  "Win32_UI_TextServices",
  "Win32_UI_WindowsAndMessaging"
]

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = "0.18"
gdkx11-sys = "0.18"
gdkwayland-sys = "0.18.0"
x11-dl = "2.21"
zbus = "3"
png = "0.17"
parking_lot = "0.12"
